// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelRaid():Promise<void>;

export function CancelRedemption(arg1:string,arg2:string):Promise<void>;

export function ClearCustomSound():Promise<void>;

export function ConnectEventSub():Promise<void>;

export function CreateCustomReward(arg1:main.CreateRewardInput):Promise<main.CustomRewardDTO>;

export function CreatePoll(arg1:string,arg2:Array<string>,arg3:number):Promise<main.PollDTO>;

export function DeleteCustomReward(arg1:string):Promise<void>;

export function DeletePollTemplate(arg1:number):Promise<void>;

export function DisconnectEventSub():Promise<void>;

export function EndPoll(arg1:string,arg2:boolean):Promise<main.PollDTO>;

export function FulfillRedemption(arg1:string,arg2:string):Promise<void>;

export function GetConnectionStatus():Promise<string>;

export function GetCustomRewards():Promise<Array<main.CustomRewardDTO>>;

export function GetFollowedLiveChannels():Promise<Array<main.RaidTargetDTO>>;

export function GetMyChannelInfo():Promise<main.ChannelInfoDTO>;

export function GetPendingRedemptions(arg1:string):Promise<Array<main.RedemptionDTO>>;

export function GetPollArchive():Promise<Array<main.ArchivedPollDTO>>;

export function GetPollTemplates():Promise<Array<main.PollTemplateDTO>>;

export function GetPolls():Promise<Array<main.PollDTO>>;

export function GetSameCategoryChannels():Promise<Array<main.RaidTargetDTO>>;

export function GetSettings():Promise<main.SettingsDTO>;

export function GetSoundDataBase64():Promise<string>;

export function GetUser():Promise<main.UserInfo>;

export function IsAuthenticated():Promise<boolean>;

export function Login():Promise<void>;

export function Logout():Promise<void>;

export function PollLogin():Promise<void>;

export function SaveCustomSound(arg1:string,arg2:string):Promise<void>;

export function SavePollTemplate(arg1:string,arg2:string,arg3:Array<string>,arg4:number):Promise<void>;

export function SaveSettings(arg1:main.SettingsDTO):Promise<void>;

export function SearchCategories(arg1:string):Promise<Array<main.CategoryDTO>>;

export function SearchRaidTargets(arg1:string):Promise<Array<main.RaidTargetDTO>>;

export function StartLogin():Promise<string>;

export function StartRaid(arg1:string):Promise<void>;

export function TestSound():Promise<void>;

export function ToggleCustomRewardPaused(arg1:string,arg2:boolean):Promise<void>;

export function UpdateChannelInfo(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function UpdateCustomReward(arg1:string,arg2:main.CreateRewardInput):Promise<main.CustomRewardDTO>;
