// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectEventSub():Promise<void>;

export function DisconnectEventSub():Promise<void>;

export function GetConnectionStatus():Promise<string>;

export function GetSettings():Promise<main.SettingsDTO>;

export function GetSoundDataBase64():Promise<string>;

export function GetUser():Promise<main.UserInfo>;

export function IsAuthenticated():Promise<boolean>;

export function Login():Promise<void>;

export function Logout():Promise<void>;

export function SaveCustomSound(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:main.SettingsDTO):Promise<void>;

export function TestSound():Promise<void>;
