// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCustomSound() {
  return window['go']['main']['App']['ClearCustomSound']();
}

export function ConnectEventSub() {
  return window['go']['main']['App']['ConnectEventSub']();
}

export function CreatePoll(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreatePoll'](arg1, arg2, arg3);
}

export function DeletePollTemplate(arg1) {
  return window['go']['main']['App']['DeletePollTemplate'](arg1);
}

export function DisconnectEventSub() {
  return window['go']['main']['App']['DisconnectEventSub']();
}

export function EndPoll(arg1, arg2) {
  return window['go']['main']['App']['EndPoll'](arg1, arg2);
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetPollArchive() {
  return window['go']['main']['App']['GetPollArchive']();
}

export function GetPollTemplates() {
  return window['go']['main']['App']['GetPollTemplates']();
}

export function GetPolls() {
  return window['go']['main']['App']['GetPolls']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSoundDataBase64() {
  return window['go']['main']['App']['GetSoundDataBase64']();
}

export function GetUser() {
  return window['go']['main']['App']['GetUser']();
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function Login() {
  return window['go']['main']['App']['Login']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function PollLogin() {
  return window['go']['main']['App']['PollLogin']();
}

export function SaveCustomSound(arg1, arg2) {
  return window['go']['main']['App']['SaveCustomSound'](arg1, arg2);
}

export function SavePollTemplate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SavePollTemplate'](arg1, arg2, arg3, arg4);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartLogin() {
  return window['go']['main']['App']['StartLogin']();
}

export function TestSound() {
  return window['go']['main']['App']['TestSound']();
}
