// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRaid() {
  return window['go']['main']['App']['CancelRaid']();
}

export function CancelRedemption(arg1, arg2) {
  return window['go']['main']['App']['CancelRedemption'](arg1, arg2);
}

export function ClearCustomSound() {
  return window['go']['main']['App']['ClearCustomSound']();
}

export function ConnectEventSub() {
  return window['go']['main']['App']['ConnectEventSub']();
}

export function CreateClip(arg1) {
  return window['go']['main']['App']['CreateClip'](arg1);
}

export function CreateCustomReward(arg1) {
  return window['go']['main']['App']['CreateCustomReward'](arg1);
}

export function CreatePoll(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreatePoll'](arg1, arg2, arg3);
}

export function CreatePrediction(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreatePrediction'](arg1, arg2, arg3);
}

export function CreateStreamMarker(arg1) {
  return window['go']['main']['App']['CreateStreamMarker'](arg1);
}

export function DeleteCustomReward(arg1) {
  return window['go']['main']['App']['DeleteCustomReward'](arg1);
}

export function DeletePollTemplate(arg1) {
  return window['go']['main']['App']['DeletePollTemplate'](arg1);
}

export function DisconnectEventSub() {
  return window['go']['main']['App']['DisconnectEventSub']();
}

export function EndPoll(arg1, arg2) {
  return window['go']['main']['App']['EndPoll'](arg1, arg2);
}

export function EndPrediction(arg1, arg2, arg3) {
  return window['go']['main']['App']['EndPrediction'](arg1, arg2, arg3);
}

export function FulfillRedemption(arg1, arg2) {
  return window['go']['main']['App']['FulfillRedemption'](arg1, arg2);
}

export function GetClips(arg1) {
  return window['go']['main']['App']['GetClips'](arg1);
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetCreatorGoals() {
  return window['go']['main']['App']['GetCreatorGoals']();
}

export function GetCustomRewards() {
  return window['go']['main']['App']['GetCustomRewards']();
}

export function GetFollowedLiveChannels() {
  return window['go']['main']['App']['GetFollowedLiveChannels']();
}

export function GetHypeTrainEvents() {
  return window['go']['main']['App']['GetHypeTrainEvents']();
}

export function GetMyChannelInfo() {
  return window['go']['main']['App']['GetMyChannelInfo']();
}

export function GetPendingRedemptions(arg1) {
  return window['go']['main']['App']['GetPendingRedemptions'](arg1);
}

export function GetPollArchive() {
  return window['go']['main']['App']['GetPollArchive']();
}

export function GetPollTemplates() {
  return window['go']['main']['App']['GetPollTemplates']();
}

export function GetPolls() {
  return window['go']['main']['App']['GetPolls']();
}

export function GetPredictions() {
  return window['go']['main']['App']['GetPredictions']();
}

export function GetSameCategoryChannels() {
  return window['go']['main']['App']['GetSameCategoryChannels']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSoundDataBase64() {
  return window['go']['main']['App']['GetSoundDataBase64']();
}

export function GetUser() {
  return window['go']['main']['App']['GetUser']();
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function Login() {
  return window['go']['main']['App']['Login']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PollLogin() {
  return window['go']['main']['App']['PollLogin']();
}

export function ProcessVoiceCommand(arg1) {
  return window['go']['main']['App']['ProcessVoiceCommand'](arg1);
}

export function SaveCustomSound(arg1, arg2) {
  return window['go']['main']['App']['SaveCustomSound'](arg1, arg2);
}

export function SavePollTemplate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SavePollTemplate'](arg1, arg2, arg3, arg4);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchCategories(arg1) {
  return window['go']['main']['App']['SearchCategories'](arg1);
}

export function SearchRaidTargets(arg1) {
  return window['go']['main']['App']['SearchRaidTargets'](arg1);
}

export function SendAnnouncement(arg1, arg2) {
  return window['go']['main']['App']['SendAnnouncement'](arg1, arg2);
}

export function SendShoutout(arg1) {
  return window['go']['main']['App']['SendShoutout'](arg1);
}

export function StartLogin() {
  return window['go']['main']['App']['StartLogin']();
}

export function StartRaid(arg1) {
  return window['go']['main']['App']['StartRaid'](arg1);
}

export function SuggestClipTitle(arg1, arg2) {
  return window['go']['main']['App']['SuggestClipTitle'](arg1, arg2);
}

export function TestSound() {
  return window['go']['main']['App']['TestSound']();
}

export function ToggleCustomRewardPaused(arg1, arg2) {
  return window['go']['main']['App']['ToggleCustomRewardPaused'](arg1, arg2);
}

export function UpdateChannelInfo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateChannelInfo'](arg1, arg2, arg3, arg4);
}

export function UpdateCustomReward(arg1, arg2) {
  return window['go']['main']['App']['UpdateCustomReward'](arg1, arg2);
}
